import sys

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import logging
import multiprocessing as mp
import os
import pandas as pd
from pathlib import Path
import subprocess
from tqdm import tqdm
from typing import Optional


def setup_logger(logfile_path: str | Path) -> logging.Logger:
    """
    Sets up a logger to be used throughout
    the main pipeline, i.e., data formatting.

    Args:
        logfile_path: Path to where the logging file can be found

    Returns:
        A logging object
    """
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    if logger.hasHandlers():
        logger.handlers.clear()

    fh = logging.FileHandler(filename=logfile_path, mode="a")
    fh.setLevel(logging.INFO)
    formatter = logging.Formatter(
        fmt="%(asctime)s - %(levelname)s - %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    fh.setFormatter(formatter)
    logger.addHandler(fh)

    return logger


def write_alignments(aln_f: str, locus_records: pd.DataFrame) -> None:
    """
    Writes locus-specific alignment files

    Args:
        aln_f: Path where the alignment file should be created
        locus_records: Dataframe containing the locus-specific sequences that should be added to the alignment
    """
    with open(aln_f, "w") as f:
        for _i, rec in locus_records.iterrows():
            seq_rec = SeqRecord(
                Seq(rec["seq"]), id=rec["individual_id"], description=""
            )
            SeqIO.write(seq_rec, f, "fasta")


class InterpolatedDataFormatter:
    """
    Formats the interpolated data generated by the DNAInterpolator
    """

    def __init__(
        self,
        in_dir: str,
        out_dir: str,
        taxonomic_group: str,
        num_workers: int = 4,
        consensus_interpolation: bool = False,
        species_aware: bool = False,
    ):
        self.in_dir = in_dir
        self.out_dir = out_dir
        self.taxonomic_group = taxonomic_group
        self.max_consensus_divergences_across_loci = pd.read_csv(
            f"{self.out_dir}/{self.taxonomic_group}_consensus_divergence_across_loci.csv",
            header=0,
        )
        self.num_workers = num_workers
        self.consensus_interpolation = consensus_interpolation
        self.species_aware = species_aware

        self.recs, self.locus_lengths = self.cat_records()
        self.consensus_seqs_per_loci = pd.read_csv(
            f"{self.out_dir}/consensus_sequences_loci.csv", header=0,
            dtype={"locus": str}
        )

        self.logger = setup_logger(f"data_prep_{self.taxonomic_group}.log")

    def cat_records(self) -> tuple:
        """
        Concatenates interpolated records with old records

        Returns:
            A tuple with original and interpolated sequences combined in a dataframe and a dictionary with loci lengths
        """
        new_recs = pd.read_csv(
            f"{self.out_dir}/records_interpolated_{self.taxonomic_group}.csv",
            header=0,
            dtype={"gene_id": str},
        )
        old_recs = pd.read_csv(f"{self.out_dir}/records_original.csv", header=0, dtype={"gene_id": str})
        recs = pd.concat([old_recs, new_recs])
        recs.sort_values(by=["species", "gene_id"], inplace=True)
        locus_lengths = {
            locus: len(old_recs.loc[old_recs["gene_id"] == locus, "seq"].values[0])
            for locus in old_recs["gene_id"].unique()
        }
        print(
            f"Concatenated records: {len(recs)} | Unique: {len(recs['seq'].unique())}"
        )
        return recs, locus_lengths

    def run(self):
        """
        Wrapper function for parallelization of formatting
        """

        for name, species_recs in self.recs.groupby(["species"]):
            name = name[0] if isinstance(name, tuple) else name

            self.logger.info(f"Checking format for species {name}")
            self.last_check(name, species_recs)

        Path(f"{self.out_dir}/alignments").mkdir(parents=True, exist_ok=True)
        Path(f"{self.out_dir}/RAxML").mkdir(parents=True, exist_ok=True)
        with mp.Pool(
            self.num_workers,
            initializer=setup_logger,
            initargs=(f"data_prep_{self.taxonomic_group}.log",),
        ) as pool:
            list(
                tqdm(
                    pool.imap(self.align_data, self.recs.groupby("gene_id")),
                    total=len(self.recs["gene_id"].unique()),
                )
            )

    def align_data(self, args: tuple) -> None:
        """
        Formats interpolated data by generating alignment files and calculating GTRGAMMA distances

        Args:
            args: The name of a locus and all records belonging to that locus.
        """
        locus = args[0]
        logger = (
            logging.getLogger()
        )  # a unique logger for this process (within multiprocessing)
        aln_f = f"{self.out_dir}/alignments/{locus}.fasta"
        if not os.path.isfile(aln_f):
            logger.info(f"Writing alignment for locus {locus}...")
            write_alignments(aln_f, args[1])
        if not os.path.isfile(f"{self.out_dir}/RAxML/RAxML_distances.{locus}"):
            logger.info(f"Running RAxML for locus {locus}...")
            self.run_raxml(aln_f)

    def last_check(self, species: str, species_recs: pd.DataFrame):
        """
        Checks that loci lengths are correct and that SNPs in concatenated sequences
        per individual do not exceed maximum divergence from consensus.

        Args:
            species: The species the current records belong to
            species_recs: A dataframe with sequences belonging to a specific species
        """
        max_divergence = self.max_consensus_divergences_across_loci.loc[
            self.max_consensus_divergences_across_loci["species"] == species,
            "divergence",
        ].values[0]

        loci = self.recs["gene_id"].unique()
        for name, individual_recs in species_recs.groupby(["individual_id"]):
            seq = ""
            name_tup = name if isinstance(name, tuple) else (name,)

            per_locus_div = 0
            for locus in loci:
                try:
                    locus_seq = individual_recs.loc[
                        individual_recs["gene_id"] == locus, "seq"
                    ].values[0]

                    locus_cons = self.consensus_seqs_per_loci.loc[
                        (self.consensus_seqs_per_loci["species"] == species)
                        & (self.consensus_seqs_per_loci["locus"] == locus), "consensus"].values[0]
                    seq_divergence = len(
                        [
                            base
                            for idx, base in enumerate(locus_seq.replace("N", "-").replace("?", "-"))
                            if base != "_" and base != locus_cons[idx]
                        ]
                    )
                    per_locus_div += seq_divergence
                except IndexError:
                    continue  # missing gene

                if len(locus_seq) != self.locus_lengths[locus]:
                    raise Exception(
                        f"Interpolated seq of individual {name_tup[0]} does not have same length as"
                        f" original data at locus {locus}. Original is {self.locus_lengths[locus]},"
                        f" interpolated is {len(locus_seq)}"
                    )

            if per_locus_div > max_divergence:
                raise Exception(
                    f"Seq divergence for individual {name[0]} is {per_locus_div} where"
                    f" max divergence is {max_divergence}"
                )

        self.logger.info(
            f"Of a total of {len(self.recs)} sequences of genus {self.taxonomic_group},"
            f" {len(self.recs['seq'].unique())} are unique"
        )

    def run_raxml(self, aln_f: str) -> None:
        """
        Runs RAxML for GTRGAMMA distance calculation outside the script.

        Args:
            aln_f: The alignment file to be used as input for RAxML
        """
        raxml_cmd = f'raxmlHPC -f x -s "{aln_f}" -m GTRGAMMA -n "{Path(aln_f).stem}" -p 12345 -T 2' \
                    f' -w "$(realpath "{self.out_dir}/RAxML")"'
        subprocess.call(raxml_cmd, shell=True)
