#################
# This template was taken from DNABERT-2 (https://github.com/MAGICS-LAB/DNABERT_2)
# We modified it to fit our code
#################
interpolation: 'balanced_interpolation'
data_local: /SOME_PATH/${interpolation}
test_local: /SOME_PATH/no_interpolation
data_local_dist: /SOME_PATH/no_interpolation/test_imbalanced.csv
data_remote: # If blank, files must be present in data_local

max_seq_len: 1276
tokenizer_name: zhihan1996/DNABERT-2-117M
feat_dim: 64

model_type: 'custom'
dist_mode: 'cosine'
genera_to_test: ['Dactylorhiza', 'Lomatium', 'Palaquium', 'Pterocarpus']

# Run Name
results_name: ${model_type}_${dist_mode}_${interpolation}
run_name: ${model_type}_${dist_mode}_${interpolation}

# Model
model:
  name: mosaic_bert
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  tokenizer_config:
      stride: 64
      return_overflowing_tokens: true
  # Mosaic BERT 'base' generally uses the default architecture values for from the Hugging Face BertConfig object
  # Note: if using the pretrained_checkpoint argument to create a model from an existing checkpoint, make sure
  # the model_config settings match the architecture of the existing model
  model_config:
    num_attention_heads: 12 # bert-base default
    num_hidden_layers: 12 # bert-base default
    attention_probs_dropout_prob: 0.0 # This must be 0 for Flash Attention with triton to work

# Dataloaders
test_loader:
  dataset:
    local: ${test_local}
    remote: ${data_remote}
    split: test
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
  drop_last: false
  num_workers: 32

optimizer:
  name: decoupled_adamw
  lr: 3e-06 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5 # Amount of weight decay regularization

algorithms:
  alibi:
      max_sequence_length: ${max_seq_len}
      train_sequence_length_scaling: 1
  low_precision_layernorm: {}

max_duration: 3ep
eval_interval: 1ep
global_train_batch_size: 48

# System
seed: 42
device_eval_batch_size: 64
device_train_microbatch_size: 12
precision: amp_bf16
dist_timeout: 300.0

# Logging
progress_bar: false
log_to_console: false
console_log_interval: 5ba
python_log_level: INFO

callbacks:
  checkpoint_saver_contrastive:
      save_path: /SOME_PATH/results/${run_name}/best

loggers_dir: logs
save_folder: /SOME_PATH/results/${run_name}/ckpt
save_folder_parent: /SOME_PATH/results/${run_name}
eval_results_path: /SOME_PATH/eval/${run_name}

